version: "3.9"

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    configs:
      - source: matomo.conf
        target: /etc/nginx/conf.d/default.conf # for Portainer

volumes:
  db:
  matomo:

configs:
  matomo.conf:
    file: ./matomo.conf
